id: I8FF89635
ocr_import_info:
  timestamp: '2023-09-27T08:52:31.706222+00:00'
  batch_id: batch-2a03
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 09:32:51.000165+00:00
last_modified: 2023-09-27 09:32:51.000172+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W10919
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW10919
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་ཆོས་མངོན་རྒྱ་མཚོའི་སྙིང་པོ།
  languages:
  - bo
  author: ཀརྨ་པ ༠༩་པ་དབང་ཕྱུག་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.8439360615841811
  ocr_word_median_confidence_index: 0.898345685
bases:
  I00KG04027:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG04027
      total_pages: 318
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG04027.txt
    statistics:
      ocr_word_median_confidence_index: 0.898345685
      ocr_word_mean_confidence_index: 0.8439360615841811
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
